<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import AdminNav from '../components/admin/AdminNav.vue'
import {adminApi,type VenuePlan} from '../api/adminApi'
import {consecutiveRows} from '../utils/adminDateTime'
const route=useRoute(),router=useRouter(),id=ref(route.params.venueId as string|undefined)
const model=ref<VenuePlan>({name:'',city:'',zones:[]}),frozen=ref(false),busy=ref(false),error=ref(''),notice=ref('')
const start=ref('A'),count=ref(10),seats=ref(50)
const total=computed(()=>model.value.zones.reduce((n,z)=>n+z.rows.reduce((a,r)=>a+Number(r.seatCount||0),0),0))
function addZone(){const n=model.value.zones.length+1;model.value.zones.push({code:'ZONE_'+n,name:'区域 '+n,rows:[]})}
function batch(index:number){try{const rows=consecutiveRows(start.value.toUpperCase(),count.value,seats.value);const zone=model.value.zones[index]!;if(rows.some(r=>zone.rows.some(old=>old.label===r.label)))throw new Error('行号重复，请调整起始行');zone.rows.push(...rows);error.value=''}catch(e){error.value=String(e)}}
onMounted(async()=>{if(id.value)try{const v=await adminApi.venue(id.value);model.value={name:v.name,city:v.city,zones:v.zones.map(z=>({code:z.code,name:z.name,rows:z.rows}))};frozen.value=v.frozen}catch(e){error.value=String(e)}})
async function save(){busy.value=true;error.value='';try{const v=await adminApi.saveVenue(id.value,model.value);id.value=v.id;frozen.value=v.frozen;notice.value=v.pricingReset?'场馆座位方案已变更，请重新配置场次区域票价':'场馆已保存';await router.replace('/admin/venues/'+v.id)}catch(e){error.value=String(e)}finally{busy.value=false}}
watch(()=>route.params.venueId,async next=>{if(next===id.value)return;id.value=next as string|undefined;notice.value='';error.value='';model.value={name:'',city:'',zones:[]};frozen.value=false;if(id.value)try{const v=await adminApi.venue(id.value);model.value={name:v.name,city:v.city,zones:v.zones.map(z=>({code:z.code,name:z.name,rows:z.rows}))};frozen.value=v.frozen}catch(e){error.value=String(e)}})
</script>
<template><main class="admin-page"><AdminNav/><h2>{{id?'场馆座位方案':'新建场馆'}}</h2><p v-if="error" role="alert" class="admin-alert">{{error}}</p><p v-if="notice" role="status" class="admin-success">{{notice}}</p><p v-if="frozen" class="admin-alert">此场馆已有正式库存，座位方案已冻结。</p><form @submit.prevent="save"><fieldset :disabled="frozen||busy"><section class="admin-panel admin-grid"><label>场馆名称<input v-model="model.name" required maxlength="200"/></label><label>城市<input v-model="model.city" required maxlength="100"/></label></section><section class="admin-panel"><h2>区域与行</h2><p class="admin-muted">不同区域可以使用相同的行号。座位编号由行号和三位数字组成，例如 A001。</p><div class="admin-grid"><label>连续行起始字母<input v-model="start" maxlength="3"/></label><label>连续行数量<input v-model.number="count" type="number" min="1" max="200"/></label><label>每行座位数<input v-model.number="seats" type="number" min="1" max="500"/></label></div><section v-for="(z,i) in model.zones" :key="i" class="admin-zone" :data-testid="'zone-'+i"><div class="admin-grid"><label>区域代码<input v-model="z.code" required maxlength="32"/></label><label>区域名称<input v-model="z.name" required maxlength="100"/></label></div><div class="admin-rows"><div v-for="(row,j) in z.rows" :key="j" class="admin-row"><label>行号<input v-model="row.label" required maxlength="16"/></label><label>座位数量<input v-model.number="row.seatCount" type="number" min="1" max="500" required/></label><button type="button" @click="z.rows.splice(j,1)">移除行</button></div></div><div class="admin-actions"><button type="button" @click="batch(i)">添加连续行</button><button type="button" @click="z.rows.push({label:'',seatCount:50})">添加单行</button><button type="button" @click="model.zones.splice(i,1)">移除区域</button><span>{{z.rows.reduce((n,r)=>n+Number(r.seatCount||0),0)}} 席</span></div></section><button type="button" @click="addZone">添加区域</button></section></fieldset><div class="admin-actions"><span class="admin-summary">{{total.toLocaleString()}} 席</span><span class="admin-muted">默认上限 20,000 席</span><button class="primary" :disabled="busy||frozen||total===0||total>20000">保存场馆</button></div></form></main></template>
